linters:
  disable-all: true
  enable:
    - bidichk
    - bodyclose
    - contextcheck
    - dogsled
    - errcheck
    - prealloc
    - mnd
    - unconvert
    - asciicheck
    - exhaustive
    - copyloopvar
    - goconst
    - whitespace
    - gocritic
    - godox
    - goprintffuncname
    - gosimple
    - govet
    - unused
    - lll
    - makezero
    - misspell
    - nilnil
    - noctx
    - staticcheck
    - predeclared
    - unparam
    - gci
    - ineffassign
    - stylecheck

# options for analysis running
run:
  go: '1.22'
  concurrency: 4
  timeout: 5m
  tests: false
  allow-parallel-runners: false

# all available settings of specific linters
linters-settings:
  dogsled:
    max-blank-identifiers: 2
  errcheck:
    check-type-assertions: true
    check-blank: true
  exhaustive:
    check-generated: false
    default-signifies-exhaustive: true
    package-scope-only: false
  goconst:
    min-len: 3
    ignore-tests: true
    match-constant: true
    numbers: true
  mnd:
    ignored-functions:
      - strings.SplitN
      - strconv.*
      - os.OpenFile
  govet:
    enable-all: true
    disable:
      - fieldalignment
  makezero:
    always: false
  misspell:
    locale: US
  stylecheck:
      checks: ["all", "-ST1003"]
  varnamelen:
    ignore-type-assert-ok: true
    ignore-map-index-ok: true
    ignore-chan-recv-ok: true
    ignore-names:
      - err
      - ch
      - ok
    ignore-decls:
      - i int
      - ch chan
  gci:
    sections:
      - standard
      - default
      - prefix(google.golang.org)
      - prefix(golang.org)
      - prefix(github.com/altessa-s)
      - prefix(github.com/altessa-s/ozzo-rules)
      - blank
      - alias
    skip-generated: false
